### PR TITLE
fixed display of dashboard for different circumstances

### PR DESCRIPTION
**Pull request by winniemzhao**
Screen Shot 2022-08-30 at 3 52 24 PM
Screen Shot 2022-08-30 at 3 52 50 PM
Screen Shot 2022-08-30 at 3 53 05 PM

### CODE REVIEW

**Comment by winniemzhao** [comment]
Screen Shot 2022-08-30 at 3 59 55 PM

**Comment by winniemzhao** [comment]
Screen Shot 2022-08-30 at 4 11 34 PM

**Comment by winniemzhao** [comment]
Screen Shot 2022-08-30 at 4 13 44 PM

**Comment by winniemzhao** [comment]
Screen Shot 2022-08-30 at 4 15 45 PM

**Review by michael-wales — APPROVED** [review]

**Pull request merged**
